version: 2
jobs:
  lint-scripts:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: shellcheck
          command: make shellcheck
  lint-charts:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: lint
          command: make lint

workflows:
  version: 2
  lint:
    jobs:
      - lint-scripts
      - lint-charts
