steps:
  - label: ":terminal: Lint Scripts"
    commands: make shellcheck
    agents:
      queue: "$BUILDKITE_AGENT_META_DATA_QUEUE"

  - label: ":helm: Lint Charts"
    commands: make lint
    agents:
      queue: "$BUILDKITE_AGENT_META_DATA_QUEUE"

  - label: ":shipit:" 
    commands: make release
    env:
      GIT_AUTHOR_NAME: "Buildkite CI"
      GIT_AUTHOR_EMAIL: "support@buildkite.com"
    branches: master