steps:
  - label: ":terminal: Lint Scripts"
    commands:
      - shellcheck -x .scripts/repo-sync.sh
      - shellcheck -x .scripts/repo-sync-local.sh
    plugins:
      - docker#v2.0.0:
          image: koalaman/shellcheck-alpine
    agents:
      queue: "$BUILDKITE_AGENT_META_DATA_QUEUE"

  - label: ":helm: Lint Charts"
    plugins:
      - docker#v2.0.0:
          image: gcr.io/kubernetes-charts-ci/test-image:v3.0.1
    commands:
      - git remote add k8s https://github.com/buildkite/charts || true
      - git fetch k8s master
      - ct lint --config test/ct.yaml
    agents:
      queue: "$BUILDKITE_AGENT_META_DATA_QUEUE"
