apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.replicasCount }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      serviceAccount: {{ .Release.Name }}
      containers:
        - name: buildkite-builder
          image: "{{ .Values.image }}-{{ .Values.dockerTag }}"
          imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
          securityContext:
            privileged: true
          resources:
            limits:
              cpu: {{ .Values.cpu }}
              memory: {{ .Values.memory }}
            requests:
              cpu: 10m
              memory: 50Mi
          env:
            # BUILDKITE AGENT ENV VARS
            - name: BUILDKITE_AGENT_VERSION
              value: "{{ .Values.agentTag }}"
            - name: BUILDKITE_AGENT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: agent-token
            - name: BUILDKITE_AGENT_META_DATA
              value: "{{ .Values.agentMeta }}"
            - name: SSH_PRIVATE_RSA_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: agent-ssh
          volumeMounts:
            - name: var-run-docker-sock
              mountPath: /var/run/docker.sock
            - name: service-key
              mountPath: /etc/service_key
      volumes:
        - name: var-run-docker-sock
          hostPath:
            path: /var/run/docker.sock
        - name: service-key
          secret:
            secretName: {{ .Release.Name }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
