{{- if .Values.gcrCreds }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-gcr
  labels:
    app: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  service-account-key.json: |-
    {{ .Values.gcpCreds }}
{{- end }}
