#
# This is the configuration file for BuildKite Agent
[agent_token]
token = "YOUR BUILDKITE TOKEN"

[ssh]
id_rsa = """
  copy YOUR_SSH_PRIVATE_KEY encoded with base64 e.g.:
  $ tr --delete '\n' < ~/.ssh/id_rsa | base64 | tr --delete '\n'
"""
