## Buildkite agent image version
## ref: https://hub.docker.com/r/buildkite/agent/
##
image:
  repository: buildkite/agent
  tag: 3.0

## Specify a imagePullPolicy
## 'Always' if imageTag is 'latest', else set to 'IfNotPresent'
## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
##
imagePullPolicy: IfNotPresent

## Replicas Set count
replicasCount: 1

## Agent meta-data, which can be used to assign jobs
agentMeta: "role=agent"

## Your Buildkite agent token
agentToken: ""

## Your ssh private key
## if you want to access private git repository
privateSshKey: ""

## GCP credentials for GCR
## base64 encoded GCP Service account json key file
gcrCreds: ""

## AWS credentials for ECR
awsCreds: ""

## Resource limits
cpu: 500m
memory: 1024Mi

## Node labels for pod assignment
## Ref: https://kubernetes.io/docs/user-guide/node-selection/
##
nodeSelector: {}
